# pyinstaller main.py --hidden-import holidays.countries

import time
import os
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import multiprocessing as mp

from mail_parser import mail_parser
from priceReader import price_reader
from catalog_update import catalog_update
from price_proc import price_proc
from personalization import personalization
from mail_sender import mail_sender
from info_module import info_module

max_log_lines = 25

host = None #"127.0.0.1" 
user = None #"postgres" 
password = None
db_name = None
default_thread_count = 2


mail_login = None
mail_password = None
Dir = None
Dir2 = None
path_to_catalogs = None
path_to_exit2 = None

autostart = False

class ThreadAction(QtCore.QThread):
    '''Класс для многопоточной работы'''
    printSignal1 = QtCore.pyqtSignal(int, str)
    printSignal2 = QtCore.pyqtSignal(int, str)
    printSignal3 = QtCore.pyqtSignal(int, str)
    printSignal4 = QtCore.pyqtSignal(int, str)
    printSignal5 = QtCore.pyqtSignal(int, str)
    printSignal6 = QtCore.pyqtSignal(int, str)
    logs = ['logs/mail_parser.log', 'logs/price_reader.log', 'logs/price_proc.log', 'logs/personalization.log',
            'logs/mail_sender.log', 'logs/catalog_update.log']

    def __init__(self, mainApp=None):
        super(ThreadAction, self).__init__()
        self.mainApp = mainApp

    def run(self):
        '''Вывод последних логов из файлов .log в окна с информацией (textBrowser)'''
        lst = [[self.logs[0], self.printSignal1], [self.logs[1], self.printSignal2], [self.logs[2], self.printSignal3],
               [self.logs[3], self.printSignal4], [self.logs[4], self.printSignal5], [self.logs[5], self.printSignal6]]

        while True:
            try:
                for id, (log, signal) in enumerate(lst):
                    if os.path.exists(log):
                        with open(log, 'r') as f:
                            l = f.readlines()[-max_log_lines:]
                            l = ''.join(l)
                            signal.emit(id, l)

            except Exception as ex:
                print('LOG Error:', ex)
            time.sleep(3)


path_to_exit3 = None
path_to_exp = None
path_to_final = None
path_to_info = None
path_to_sended = None

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(889, 870)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.StartButton_2 = QtWidgets.QPushButton(self.tab_4)
        self.StartButton_2.setObjectName("StartButton_2")
        self.horizontalLayout_16.addWidget(self.StartButton_2)
        self.Pause_2 = QtWidgets.QCheckBox(self.tab_4)
        self.Pause_2.setObjectName("Pause_2")
        self.horizontalLayout_16.addWidget(self.Pause_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem)
        self.verticalLayout_15.addLayout(self.horizontalLayout_16)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_15.addWidget(self.label_7)
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_1.setFont(font)
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.verticalLayout_15.addWidget(self.textBrowser_1)
        self.gridLayout_9.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Select_price_3 = QtWidgets.QPushButton(self.tab)
        self.Select_price_3.setObjectName("Select_price_3")
        self.horizontalLayout_10.addWidget(self.Select_price_3)
        self.Pause_3 = QtWidgets.QCheckBox(self.tab)
        self.Pause_3.setObjectName("Pause_3")
        self.horizontalLayout_10.addWidget(self.Pause_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.gridLayout_8.addLayout(self.horizontalLayout_10, 0, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.ThreadSpinBox_3 = QtWidgets.QSpinBox(self.tab)
        self.ThreadSpinBox_3.setMinimum(1)
        self.ThreadSpinBox_3.setMaximum(10)
        self.ThreadSpinBox_3.setProperty("value", default_thread_count)
        self.ThreadSpinBox_3.setObjectName("ThreadSpinBox_3")
        self.horizontalLayout_11.addWidget(self.ThreadSpinBox_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.gridLayout_8.addLayout(self.horizontalLayout_11, 2, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 337, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 3, 1, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_11.addWidget(self.textBrowser_2)
        self.gridLayout_8.addLayout(self.verticalLayout_11, 4, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.Start_1 = QtWidgets.QPushButton(self.tab_3)
        self.Start_1.setObjectName("Start_1")
        self.horizontalLayout_17.addWidget(self.Start_1)
        self.Pause_1 = QtWidgets.QCheckBox(self.tab_3)
        self.Pause_1.setObjectName("Pause_1")
        self.horizontalLayout_17.addWidget(self.Pause_1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.verticalLayout_18.addLayout(self.horizontalLayout_17)
        spacerItem7 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_18.addItem(spacerItem7)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_18.addWidget(self.label_2)
        self.ThreadSpinBox_1 = QtWidgets.QSpinBox(self.tab_3)
        self.ThreadSpinBox_1.setMinimum(1)
        self.ThreadSpinBox_1.setMaximum(10)
        self.ThreadSpinBox_1.setProperty("value", default_thread_count)
        self.ThreadSpinBox_1.setObjectName("ThreadSpinBox_1")
        self.horizontalLayout_18.addWidget(self.ThreadSpinBox_1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem8)
        self.verticalLayout_18.addLayout(self.horizontalLayout_18)
        spacerItem9 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_18.addItem(spacerItem9)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem10)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_17.addWidget(self.label_8)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_17.addWidget(self.textBrowser_3)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.gridLayout_10.addLayout(self.verticalLayout_18, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StartButton_6 = QtWidgets.QPushButton(self.tab_6)
        self.StartButton_6.setObjectName("StartButton_6")
        self.horizontalLayout.addWidget(self.StartButton_6)
        self.Pause_6 = QtWidgets.QCheckBox(self.tab_6)
        self.Pause_6.setObjectName("Pause_6")
        self.horizontalLayout.addWidget(self.Pause_6)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem12 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.ThreadSpinBox_4 = QtWidgets.QSpinBox(self.tab_6)
        self.ThreadSpinBox_4.setMinimum(1)
        self.ThreadSpinBox_4.setMaximum(10)
        self.ThreadSpinBox_4.setProperty("value", default_thread_count)
        self.ThreadSpinBox_4.setObjectName("ThreadSpinBox_4")
        self.horizontalLayout_2.addWidget(self.ThreadSpinBox_4)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem14 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.UpdateButton_table = QtWidgets.QPushButton(self.tab_6)
        self.UpdateButton_table.setObjectName("UpdateButton_table")
        self.horizontalLayout_4.addWidget(self.UpdateButton_table)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.PricesTable_6 = QtWidgets.QTableWidget(self.tab_6)
        self.PricesTable_6.setObjectName("PricesTable_6")
        self.PricesTable_6.setColumnCount(0)
        self.PricesTable_6.setRowCount(0)
        self.verticalLayout_2.addWidget(self.PricesTable_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.UpdateButton_all = QtWidgets.QPushButton(self.tab_6)
        self.UpdateButton_all.setMinimumSize(QtCore.QSize(119, 0))
        self.UpdateButton_all.setObjectName("UpdateButton_all")
        self.horizontalLayout_3.addWidget(self.UpdateButton_all)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.UpdateButton_selected = QtWidgets.QPushButton(self.tab_6)
        self.UpdateButton_selected.setObjectName("UpdateButton_selected")
        self.horizontalLayout_3.addWidget(self.UpdateButton_selected)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem17 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_3.addWidget(self.textBrowser_4)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 4, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem18, 1, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.StartButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.StartButton_7.setObjectName("StartButton_7")
        self.horizontalLayout_6.addWidget(self.StartButton_7)
        self.Pause_7 = QtWidgets.QCheckBox(self.tab_2)
        self.Pause_7.setObjectName("Pause_7")
        self.horizontalLayout_6.addWidget(self.Pause_7)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem20)
        self.verticalLayout_19.addLayout(self.horizontalLayout_6)
        spacerItem21 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_19.addItem(spacerItem21)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_21.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_21.setSpacing(5)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem22 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem22)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem23)
        self.UpdateButton_table_2 = QtWidgets.QPushButton(self.tab_2)
        self.UpdateButton_table_2.setObjectName("UpdateButton_table_2")
        self.horizontalLayout_22.addWidget(self.UpdateButton_table_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.PricesTable_7 = QtWidgets.QTableWidget(self.tab_2)
        self.PricesTable_7.setObjectName("PricesTable_7")
        self.PricesTable_7.setColumnCount(0)
        self.PricesTable_7.setRowCount(0)
        self.verticalLayout_4.addWidget(self.PricesTable_7)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.SendButton_all = QtWidgets.QPushButton(self.tab_2)
        self.SendButton_all.setMinimumSize(QtCore.QSize(119, 0))
        self.SendButton_all.setObjectName("SendButton_all")
        self.horizontalLayout_23.addWidget(self.SendButton_all)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem24)
        self.SendButton_selected = QtWidgets.QPushButton(self.tab_2)
        self.SendButton_selected.setObjectName("SendButton_selected")
        self.horizontalLayout_23.addWidget(self.SendButton_selected)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_21.addLayout(self.verticalLayout_4)
        spacerItem25 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem25)
        self.verticalLayout_19.addLayout(self.horizontalLayout_21)
        spacerItem26 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_19.addItem(spacerItem26)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.verticalLayout_5.addWidget(self.textBrowser_5)
        self.verticalLayout_19.addLayout(self.verticalLayout_5)
        self.gridLayout_3.addLayout(self.verticalLayout_19, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem27, 3, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.StartButton_5 = QtWidgets.QPushButton(self.tab_5)
        self.StartButton_5.setObjectName("StartButton_5")
        self.horizontalLayout_9.addWidget(self.StartButton_5)
        self.Pause_5 = QtWidgets.QCheckBox(self.tab_5)
        self.Pause_5.setObjectName("Pause_5")
        self.horizontalLayout_9.addWidget(self.Pause_5)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem28)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 4, 0, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem29, 1, 1, 1, 1)
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_6.setFont(font)
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.gridLayout_6.addWidget(self.textBrowser_6, 5, 0, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem30)
        self.groupBox = QtWidgets.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.timeEdit.setFont(font)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_4.addWidget(self.timeEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.timeEdit_2.setFont(font)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.gridLayout_4.addWidget(self.timeEdit_2, 1, 1, 1, 1)
        self.base_price_button = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.base_price_button.setFont(font)
        self.base_price_button.setObjectName("base_price_button")
        self.gridLayout_4.addWidget(self.base_price_button, 0, 2, 1, 1)
        self.mass_offers_button = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.mass_offers_button.setFont(font)
        self.mass_offers_button.setObjectName("mass_offers_button")
        self.gridLayout_4.addWidget(self.mass_offers_button, 1, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        spacerItem31 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_6.addItem(spacerItem31)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem32)
        self.SaveButton_5 = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.SaveButton_5.setFont(font)
        self.SaveButton_5.setObjectName("SaveButton_5")
        self.horizontalLayout_7.addWidget(self.SaveButton_5)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem33)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem34)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 2, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem35 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem35, 1, 6, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem36, 3, 4, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem37)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.create_report_button = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.create_report_button.setFont(font)
        self.create_report_button.setObjectName("create_report_button")
        self.horizontalLayout_24.addWidget(self.create_report_button)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem38)
        self.reset_repotr_button = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.reset_repotr_button.setFont(font)
        self.reset_repotr_button.setObjectName("reset_repotr_button")
        self.horizontalLayout_24.addWidget(self.reset_repotr_button)
        self.gridLayout_11.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.horizontalLayout_20.addWidget(self.groupBox_3)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem39)
        self.gridLayout_16.addLayout(self.horizontalLayout_20, 4, 2, 1, 1)
        spacerItem40 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem40, 5, 5, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem41, 1, 0, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem42, 7, 3, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem43)
        self.Errors_resert = QtWidgets.QPushButton(self.tab_7)
        self.Errors_resert.setObjectName("Errors_resert")
        self.horizontalLayout_19.addWidget(self.Errors_resert)
        self.gridLayout_16.addLayout(self.horizontalLayout_19, 2, 1, 1, 2)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem44)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.create_mail_report_button = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.create_mail_report_button.setFont(font)
        self.create_mail_report_button.setObjectName("create_mail_report_button")
        self.horizontalLayout_26.addWidget(self.create_mail_report_button)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem45)
        self.reset_mail_repotr_button = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.reset_mail_repotr_button.setFont(font)
        self.reset_mail_repotr_button.setObjectName("reset_mail_repotr_button")
        self.horizontalLayout_26.addWidget(self.reset_mail_repotr_button)
        self.gridLayout_14.addLayout(self.horizontalLayout_26, 0, 0, 1, 1)
        self.horizontalLayout_25.addWidget(self.groupBox_4)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem46)
        self.gridLayout_16.addLayout(self.horizontalLayout_25, 6, 2, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem47, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(-1, 15, -1, -1)
        self.gridLayout_12.setVerticalSpacing(8)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.Module_status_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Module_status_4.setFont(font)
        self.Module_status_4.setStyleSheet("color:red;\n"
                                           "")
        self.Module_status_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Module_status_4.setObjectName("Module_status_4")
        self.gridLayout_12.addWidget(self.Module_status_4, 5, 1, 1, 1)
        self.Module_status_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Module_status_6.setFont(font)
        self.Module_status_6.setStyleSheet("color:red;\n"
                                           "")
        self.Module_status_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Module_status_6.setObjectName("Module_status_6")
        self.gridLayout_12.addWidget(self.Module_status_6, 7, 1, 1, 1)
        self.Module_status_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Module_status_5.setFont(font)
        self.Module_status_5.setStyleSheet("color:red;\n"
                                           "")
        self.Module_status_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Module_status_5.setObjectName("Module_status_5")
        self.gridLayout_12.addWidget(self.Module_status_5, 6, 1, 1, 1)
        self.Module_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Module_5.setFont(font)
        self.Module_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.Module_5.setObjectName("Module_5")
        self.gridLayout_12.addWidget(self.Module_5, 6, 0, 1, 1)
        self.Module_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Module_6.setFont(font)
        self.Module_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.Module_6.setObjectName("Module_6")
        self.gridLayout_12.addWidget(self.Module_6, 7, 0, 1, 1)
        self.Module_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Module_2.setFont(font)
        self.Module_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.Module_2.setObjectName("Module_2")
        self.gridLayout_12.addWidget(self.Module_2, 3, 0, 1, 1)
        self.Module_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Module_4.setFont(font)
        self.Module_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.Module_4.setObjectName("Module_4")
        self.gridLayout_12.addWidget(self.Module_4, 5, 0, 1, 1)
        self.Module_status_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Module_status_2.setFont(font)
        self.Module_status_2.setStyleSheet("color:red;\n"
                                           "")
        self.Module_status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Module_status_2.setObjectName("Module_status_2")
        self.gridLayout_12.addWidget(self.Module_status_2, 3, 1, 1, 1)
        self.Module_header = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Module_header.setFont(font)
        self.Module_header.setAlignment(QtCore.Qt.AlignCenter)
        self.Module_header.setObjectName("Module_header")
        self.gridLayout_12.addWidget(self.Module_header, 0, 0, 1, 1)
        self.Module_status_header = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Module_status_header.setFont(font)
        self.Module_status_header.setAlignment(QtCore.Qt.AlignCenter)
        self.Module_status_header.setObjectName("Module_status_header")
        self.gridLayout_12.addWidget(self.Module_status_header, 0, 1, 1, 1)
        self.Module_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Module_3.setFont(font)
        self.Module_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.Module_3.setObjectName("Module_3")
        self.gridLayout_12.addWidget(self.Module_3, 4, 0, 1, 1)
        self.Module_status_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Module_status_3.setFont(font)
        self.Module_status_3.setStyleSheet("color:red;\n"
                                           "")
        self.Module_status_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Module_status_3.setObjectName("Module_status_3")
        self.gridLayout_12.addWidget(self.Module_status_3, 4, 1, 1, 1)
        self.UpdateTime_item_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.UpdateTime_item_4.setFont(font)
        self.UpdateTime_item_4.setText("")
        self.UpdateTime_item_4.setAlignment(QtCore.Qt.AlignCenter)
        self.UpdateTime_item_4.setObjectName("UpdateTime_item_4")
        self.gridLayout_12.addWidget(self.UpdateTime_item_4, 5, 2, 1, 1)
        self.UpdateTime_item_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.UpdateTime_item_3.setFont(font)
        self.UpdateTime_item_3.setText("")
        self.UpdateTime_item_3.setAlignment(QtCore.Qt.AlignCenter)
        self.UpdateTime_item_3.setObjectName("UpdateTime_item_3")
        self.gridLayout_12.addWidget(self.UpdateTime_item_3, 4, 2, 1, 1)
        self.UpdateTime_item_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.UpdateTime_item_5.setFont(font)
        self.UpdateTime_item_5.setText("")
        self.UpdateTime_item_5.setAlignment(QtCore.Qt.AlignCenter)
        self.UpdateTime_item_5.setObjectName("UpdateTime_item_5")
        self.gridLayout_12.addWidget(self.UpdateTime_item_5, 6, 2, 1, 1)
        self.UpdateTime_item_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.UpdateTime_item_6.setFont(font)
        self.UpdateTime_item_6.setText("")
        self.UpdateTime_item_6.setAlignment(QtCore.Qt.AlignCenter)
        self.UpdateTime_item_6.setObjectName("UpdateTime_item_6")
        self.gridLayout_12.addWidget(self.UpdateTime_item_6, 7, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_12.addWidget(self.line, 1, 1, 1, 1)
        self.UpdateTime_item_1 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.UpdateTime_item_1.setFont(font)
        self.UpdateTime_item_1.setText("")
        self.UpdateTime_item_1.setAlignment(QtCore.Qt.AlignCenter)
        self.UpdateTime_item_1.setObjectName("UpdateTime_item_1")
        self.gridLayout_12.addWidget(self.UpdateTime_item_1, 2, 2, 1, 1)
        self.UpdateTime_item_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.UpdateTime_item_2.setFont(font)
        self.UpdateTime_item_2.setText("")
        self.UpdateTime_item_2.setAlignment(QtCore.Qt.AlignCenter)
        self.UpdateTime_item_2.setObjectName("UpdateTime_item_2")
        self.gridLayout_12.addWidget(self.UpdateTime_item_2, 3, 2, 1, 1)
        self.UpdateTime_header = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UpdateTime_header.setFont(font)
        self.UpdateTime_header.setObjectName("UpdateTime_header")
        self.gridLayout_12.addWidget(self.UpdateTime_header, 0, 2, 1, 1)
        self.Module_status_1 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Module_status_1.setFont(font)
        self.Module_status_1.setStyleSheet("color:red;\n"
                                           "")
        self.Module_status_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Module_status_1.setObjectName("Module_status_1")
        self.gridLayout_12.addWidget(self.Module_status_1, 2, 1, 1, 1)
        self.Module_1 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Module_1.setFont(font)
        self.Module_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.Module_1.setObjectName("Module_1")
        self.gridLayout_12.addWidget(self.Module_1, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_12.addWidget(self.line_3, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_12.addWidget(self.line_2, 1, 0, 1, 1)
        self.Errors_header = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Errors_header.setFont(font)
        self.Errors_header.setAlignment(QtCore.Qt.AlignCenter)
        self.Errors_header.setObjectName("Errors_header")
        self.gridLayout_12.addWidget(self.Errors_header, 0, 3, 1, 1)
        self.Errors_1 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Errors_1.setFont(font)
        self.Errors_1.setAlignment(QtCore.Qt.AlignCenter)
        self.Errors_1.setObjectName("Errors_1")
        self.gridLayout_12.addWidget(self.Errors_1, 2, 3, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_12.addWidget(self.line_4, 1, 3, 1, 1)
        self.Errors_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Errors_2.setFont(font)
        self.Errors_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Errors_2.setObjectName("Errors_2")
        self.gridLayout_12.addWidget(self.Errors_2, 3, 3, 1, 1)
        self.Errors_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Errors_3.setFont(font)
        self.Errors_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Errors_3.setObjectName("Errors_3")
        self.gridLayout_12.addWidget(self.Errors_3, 4, 3, 1, 1)
        self.Errors_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Errors_4.setFont(font)
        self.Errors_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Errors_4.setObjectName("Errors_4")
        self.gridLayout_12.addWidget(self.Errors_4, 5, 3, 1, 1)
        self.Errors_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Errors_5.setFont(font)
        self.Errors_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Errors_5.setObjectName("Errors_5")
        self.gridLayout_12.addWidget(self.Errors_5, 6, 3, 1, 1)
        self.Errors_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.Errors_6.setFont(font)
        self.Errors_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Errors_6.setObjectName("Errors_6")
        self.gridLayout_12.addWidget(self.Errors_6, 7, 3, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_2, 1, 1, 1, 3)
        self.tabWidget.addTab(self.tab_7, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 889, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ###
        self.host = host
        self.user = user
        self.password = password
        self.db_name = db_name
        self.mail_login = mail_login
        self.mail_password = mail_password
        self.Dir = Dir
        self.Dir2 = Dir2
        self.path_to_catalogs = path_to_catalogs
        self.path_to_exit2 = path_to_exit2
        self.path_to_exit3 = path_to_exit3
        self.path_to_exp = path_to_exp
        self.path_to_final = path_to_final
        self.path_to_info = path_to_info
        self.path_to_sended = path_to_sended
        self.default_thread_count = default_thread_count

        self.refresh_log()

        self.mail_parser = mail_parser(self)
        self.price_reader = price_reader(self)
        self.catalog_update = catalog_update(self)
        self.price_proc = price_proc(self)
        self.personalization = personalization(self)
        self.mail_sender = mail_sender(self)
        self.info_module = info_module(self)

        self.info_module.Start()
        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartButton_2.setText(_translate("MainWindow", "Запуск"))
        self.Pause_2.setText(_translate("MainWindow", "Пауза"))
        self.label_7.setText(_translate("MainWindow", "Информация:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Почта"))
        self.Select_price_3.setText(_translate("MainWindow", "Запуск"))
        self.Pause_3.setText(_translate("MainWindow", "Пауза"))
        self.label_5.setText(_translate("MainWindow", "Потоки:"))
        self.label_9.setText(_translate("MainWindow", "Информация:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Настройка импорта файла"))
        self.Start_1.setText(_translate("MainWindow", "Запуск"))
        self.Pause_1.setText(_translate("MainWindow", "Пауза"))
        self.label_2.setText(_translate("MainWindow", "Потоки:"))
        self.label_8.setText(_translate("MainWindow", "Информация:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Обработка прайсов"))
        self.StartButton_6.setText(_translate("MainWindow", "Запуск"))
        self.Pause_6.setText(_translate("MainWindow", "Пауза"))
        self.label_10.setText(_translate("MainWindow", "Потоки:"))
        self.UpdateButton_table.setText(_translate("MainWindow", "Обновить данные в таблице"))
        self.UpdateButton_all.setText(_translate("MainWindow", "Обновить все"))
        self.UpdateButton_selected.setText(_translate("MainWindow", "Обновить выбранные"))
        self.label_14.setText(_translate("MainWindow", "Информация:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Персонализация"))
        self.StartButton_7.setText(_translate("MainWindow", "Запуск"))
        self.Pause_7.setText(_translate("MainWindow", "Пауза"))
        self.UpdateButton_table_2.setText(_translate("MainWindow", "Обновить данные в таблице"))
        self.SendButton_all.setText(_translate("MainWindow", "Отправить все"))
        self.SendButton_selected.setText(_translate("MainWindow", "Отправить выбранные"))
        self.label_15.setText(_translate("MainWindow", "Информация:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Рассылка"))
        self.StartButton_5.setText(_translate("MainWindow", "Запуск"))
        self.Pause_5.setText(_translate("MainWindow", "Пауза"))
        self.label_13.setText(_translate("MainWindow", "Информация:"))
        self.groupBox.setTitle(_translate("MainWindow", "Время обновлений:"))
        self.label.setText(_translate("MainWindow", "Справочник Базовая цена:"))
        self.label_6.setText(_translate("MainWindow", "Справочник Предложений в опте:"))
        self.base_price_button.setText(_translate("MainWindow", "Сформировать"))
        self.mass_offers_button.setText(_translate("MainWindow", "Сформировать"))
        self.SaveButton_5.setText(_translate("MainWindow", "Сохранить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Обновление справочников"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Отчёт о состоянии прайсов"))
        self.create_report_button.setText(_translate("MainWindow", "Создать отчёт"))
        self.reset_repotr_button.setText(_translate("MainWindow", "Обнулить отчёт"))
        self.Errors_resert.setText(_translate("MainWindow", "Обновить счётчик ошибок"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Отчёт о несохранённых письмах"))
        self.create_mail_report_button.setText(_translate("MainWindow", "Создать отчёт"))
        self.reset_mail_repotr_button.setText(_translate("MainWindow", "Обнулить отчёт"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Информация о модулях"))
        self.Module_status_4.setText(_translate("MainWindow", "Пауза"))
        self.Module_status_6.setText(_translate("MainWindow", "Пауза"))
        self.Module_status_5.setText(_translate("MainWindow", "Пауза"))
        self.Module_5.setText(_translate("MainWindow", "Рассылка:"))
        self.Module_6.setText(_translate("MainWindow", "Обновление справочников:"))
        self.Module_2.setText(_translate("MainWindow", "Настройка импорта файла:"))
        self.Module_4.setText(_translate("MainWindow", "Персонализация:"))
        self.Module_status_2.setText(_translate("MainWindow", "Пауза"))
        self.Module_header.setText(_translate("MainWindow", "Модуль"))
        self.Module_status_header.setText(_translate("MainWindow", "Статус"))
        self.Module_3.setText(_translate("MainWindow", "Обработка прайсов:"))
        self.Module_status_3.setText(_translate("MainWindow", "Пауза"))
        self.UpdateTime_header.setText(_translate("MainWindow", "Время последнего действия"))
        self.Module_status_1.setText(_translate("MainWindow", "Пауза"))
        self.Module_1.setText(_translate("MainWindow", "Почта:"))
        self.Errors_header.setText(_translate("MainWindow", "Ошибки"))
        self.Errors_1.setText(_translate("MainWindow", "0"))
        self.Errors_2.setText(_translate("MainWindow", "0"))
        self.Errors_3.setText(_translate("MainWindow", "0"))
        self.Errors_4.setText(_translate("MainWindow", "0"))
        self.Errors_5.setText(_translate("MainWindow", "0"))
        self.Errors_6.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Информация"))

    def add_functions(self):
        self.StartButton_2.clicked.connect(self.mail_parser.start)
        self.Pause_2.clicked.connect(self.mail_parser.stop)

        # self.AddButton_3.clicked.connect(self.price_reader.add_FilesTable) #
        # self.AddButton_3_.clicked.connect(self.price_reader.add_SettingsTable) #
        # self.RemoveButton_3.clicked.connect(self.price_reader.preRemove) #
        # self.RemoveButton_3_.clicked.connect(self.price_reader.remove_SettingsTable) #
        # self.Load_db_3.clicked.connect(self.price_reader.load_db) #
        # self.create_report_button_1.clicked.connect(self.price_reader.create_report)
        # self.reset_repotr_button_1.clicked.connect(self.price_reader.reset_report)

        self.Start_1.clicked.connect(self.price_proc.StartProcess)
        # self.create_report_button_2.clicked.connect(self.price_proc.create_report)
        # self.reset_repotr_button_2.clicked.connect(self.price_proc.reset_report)

        # self.SaveButton_3.clicked.connect(self.price_reader.save) #
        # self.SaveButton_3_.clicked.connect(self.price_reader.save_SettingsTable) #
        self.Select_price_3.clicked.connect(self.price_reader.StartMainProc)

        self.StartButton_5.clicked.connect(self.catalog_update.start)
        self.SaveButton_5.clicked.connect(self.catalog_update.save_time)
        self.base_price_button.clicked.connect(self.catalog_update.create_base_price_report)
        self.mass_offers_button.clicked.connect(self.catalog_update.create_mass_offers_report)

        self.StartButton_6.clicked.connect(self.personalization.StartProcess)
        self.UpdateButton_table.clicked.connect(self.personalization.UpdateTable)
        self.UpdateButton_selected.clicked.connect(self.personalization.UpdateSelected)
        self.UpdateButton_all.clicked.connect(self.personalization.UpdateAll)

        self.StartButton_7.clicked.connect(self.mail_sender.StartProcess)
        self.UpdateButton_table_2.clicked.connect(self.mail_sender.UpdateTable)
        self.SendButton_all.clicked.connect(self.mail_sender.SendAll)
        self.SendButton_selected.clicked.connect(self.mail_sender.SendSelected)

        self.Errors_resert.clicked.connect(self.info_module.Restart)
        self.create_report_button.clicked.connect(self.info_module.Create_report)
        self.reset_repotr_button.clicked.connect(lambda _, s="delete from price_report": self.info_module.reset_report(s))
        self.create_mail_report_button.clicked.connect(self.info_module.Create_mail_report)
        self.reset_mail_repotr_button.clicked.connect(lambda _, s="delete from mail_report_tab": self.info_module.reset_report(s))

        # AUTO START
        if os.path.exists('autostart.txt'): #autostart:
            self.mail_parser.start()
            self.price_proc.StartProcess()
            self.price_reader.StartMainProc()
            # self.personalization.StartProcess()
            # self.mail_sender.StartProcess()
            self.catalog_update.start()

    def refresh_log(self):
        '''Обновление всех окон (textBrowser) с логами'''
        self.t = ThreadAction(self)
        self.logs_list = [[self.textBrowser_1, self.t.printSignal1], [self.textBrowser_2, self.t.printSignal2],
                          [self.textBrowser_3, self.t.printSignal3], [self.textBrowser_4, self.t.printSignal4],
                          [self.textBrowser_5, self.t.printSignal5], [self.textBrowser_6, self.t.printSignal6]]

        for tb, ps in self.logs_list:
            ps.connect(self.print_log)

        self.t.start()

    def print_log(self, id, t):
        self.logs_list[id][0].setPlainText(t)
        self.logs_list[id][0].moveCursor(QtGui.QTextCursor.End)


if __name__ == "__main__":
    try:
        if len(sys.argv) >= 2:
            autostart = sys.argv[1]

        mp.freeze_support() # для многопоточной работы

        # файл с настройками
        text = ["host:\n", "user:\n", "password:\n", "db_name:\n", "Адрес почты получателя:\n",
                "Пароль (IMAP):\n", "Папка для сырых файлов (1):\n", "Папка для сырых файлов (1.1):\n", "Папка для справочников:\n",
                "Путь до обработанных данных (2):\n", "Путь до обработанных данных (3):\n", "Путь до исключенных данных:\n",
                "Путь до итоговых прайсов:\n", "Путь до итоговых прайсов (расширенный формат):\n", "Путь до отправленных прайсов:\n",
                "Количество потоков:\n"]
        if not 'Settings.txt' in os.listdir():
            with open('Settings.txt', 'w', encoding='utf-8') as settings:
                settings.writelines(text)
        with open('Settings.txt', 'r', encoding='utf-8') as settings:
            host = settings.readline().lstrip(text[0]).strip()
            user = settings.readline().lstrip(text[1]).strip()
            password = settings.readline().lstrip(text[2]).strip()
            db_name = settings.readline().lstrip(text[3]).strip()
            mail_login = settings.readline().lstrip(text[4]).strip()
            mail_password = settings.readline().lstrip(text[5]).strip()
            Dir = settings.readline().lstrip(text[6]).strip()
            Dir2 = settings.readline().lstrip(text[7]).strip()
            path_to_catalogs = settings.readline().lstrip(text[8]).strip()
            path_to_exit2 = settings.readline().lstrip(text[9]).strip()
            path_to_exit3 = settings.readline().lstrip(text[10]).strip()
            path_to_exp = settings.readline().lstrip(text[11]).strip()
            path_to_final = settings.readline().lstrip(text[12]).strip()
            path_to_info = settings.readline().lstrip(text[13]).strip()
            path_to_sended = settings.readline().lstrip(text[14]).strip()
            default_thread_count = int(settings.readline().lstrip(text[15]).strip())

        if host == '' or user == '' or password == '' or db_name == '' or mail_login == '' or mail_password == '' or \
                 Dir == '' or path_to_catalogs == '' or path_to_exit2 == '' or path_to_exit3 == '' or path_to_exp == '' or \
                path_to_final == '' or path_to_info == '' or path_to_sended == '':
            print("Заполните Settings.txt")
            time.sleep(5)
            exit(0)

        dirs = ['Archives', 'tmp_', 'logs', fr"{path_to_catalogs}/Справочник Базовая цена", fr"{path_to_catalogs}/pre Справочник Базовая цена",
                fr"{path_to_catalogs}/Справочник Предложений в опте", fr"{path_to_catalogs}/pre Справочник Предложений в опте"]
        for dr in dirs:
            if not os.path.exists(dr):
                os.mkdir(dr)

        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())

    except Exception as mainEx:
        print(mainEx)
        _ = input()